name: {{ cookiecutter.project_name.lower().replace(' ', '_') }}
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytest
  - matplotlib
  - cartopy
  - cmocean
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - scipy
  - tqdm
  - xarray
  - netcdf4
  - palettable
  - sphinx
  - nbsphinx
  - myst-parser
  - dask
  - distributed
  - bottleneck
  - gsw
  - python-box
  - yaml
  - pip
  - pip:
    - furo
    - sphinx-autobuild
    - sphinx_math_dollar
    - sphinxcontrib.bibtex
    - watchmagic
    - jupytext
    - "-e /Users/gunnar/Projects/python/gvpy"
    - "-e ."
