name: {{ cookiecutter.project_name.lower().replace(' ', '_') }}
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - python=3.8
  - ipympl
  - ipdb
  - black
  - ipykernel
  - ipython
  - jupyter
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - matplotlib
  - cartopy
  - cmocean
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - scipy
  - tqdm
  - xarray
  - netcdf4
  - palettable
  - sphinx
  - nbsphinx
  - myst-parser
  - dask
  - distributed
  - bottleneck
  - gsw
  - python-box
  - pip
  - pip:
    - furo
    - sphinx-autobuild
    - sphinx_math_dollar
    - sphinxcontrib.bibtex
    - watchmagic
    - jupytext
    - "-e /Users/gunnar/Projects/python/gvpy"
    - "-e ."
